[package]
name = "async_concurrent_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
rand = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = "0.12.19"
